#!/bin/zsh

# Array of CRL URLs
CRL_URLS=(
    "https://www.apple.com/appleca/root.crl"
    "https://www.apple.com/certificateauthority/root.crl"
    "https://crl.apple.com/softwareupdateca.crl"
    "https://crl.apple.com/timestamp.crl"
    "https://developer.apple.com/certificationauthority/wwdrca.crl"
    "https://crl.apple.com/apsrsa12g1.crl"
    "https://crl.apple.com/apsecc12g1.crl"
    "https://crl.apple.com/appleistca2g1.crl"
    "https://crl.apple.com/appleistca8g1.crl"
    "https://crl.apple.com/apevsrsa1g1.crl"
    "https://crl.apple.com/apevsrsa2g1.crl"
    "https://crl.apple.com/apevsrsaca3g1.crl"
    "https://crl.apple.com/apevsecc1g1.crl"
    "https://crl.apple.com/aptrsa1g1.crl"
    "https://crl.apple.com/aptecc1g1.crl"
    "http://rootca2009-crl3.e-szigno.hu/rootca2009.crl"
    "http://crl.rootca3.amazontrust.com/rootca3.crl"
    "http://crl.pki.fraunhofer.de/fhg-root-ca-2007.crl"
    "http://crl.globalsign.com/trustrootsha2g2.crl"
    "http://rootweb.managed.entrust.com/CRLs/EMSRootCA2.crl"
    "http://crl.godaddy.com/repository/gdroot-g2.crl"
    "http://www.cnnic.cn/download/rootcrl/CRL1.crl"
    "http://crl3.digicert.com/Omniroot2025.crl"
    "http://crl.camerfirma.com/chambersroot-2008.crl"
    "http://crl-2.trust.teliasonera.com/teliasonerarootcav1.crl"
    "http://vgisca142.crl.omniroot.com/vgisca142.crl"
    "http://crl.swissdigicert.ch/sdcs-root.crl"
    "http://cdp.elektronicznypodpis.pl/root_ca2.crl"
    "http://crl.pki.abb.com/Omniroot.crl"
    "http://www.signtrust.de/crl/dpsigntrust/nqsig/stcert_root_ca5.crl"
    "http://cdp1.pca.dfn.de/global-root-ca/pub/crl/cacrl.crl"
    "http://secure.globalsign.net/crl/root.crl"
    "http://crl1.camerfirma.com/chambersignroot-2008.crl"
    "http://crl1.e-tugra.com/etugra_root.crl"
    "http://crl.ws.symantec.com/universal-root.crl"
    "http://crl.root-x1.letsencrypt.org"
    "http://crl.omniroot.com/PublicSureServerSV.crl"
    "http://validation.identrust.com/crl/commercialrootca1.crl"
    "http://crl.pki.wayport.net/rootcag3.crl"
    "http://ca.disig.sk/rootcar2/crl/rootcar2.crl"
    "http://crl.swissdigicert.ch/sdcs-root2.crl"
    "http://rootca2009-crl2.e-szigno.hu/rootca2009.crl"
    "http://crl1.camerfirma.com/chambersroot.crl"
    "http://crl.godaddy.com/gdroot-g2.crl"
    "http://cdp1.disig.sk/rootcar2/crl/rootcar2.crl"
    "http://ca.disig.sk/rootcar1/crl/rootcar1.crl"
    "http://www.chenega.com/pki/rootca.crl"
    "http://crl.globalsign.com/gs/trustrootg2.crl"
    "http://crl.starfieldtech.com/sfroot-g2.crl"
    "http://crl.entrust.net/rootca1.crl"
    "http://get-crl.certificat.com/public/opentrustrootcag3.crl"
    "http://crl.firmaprofesional.com/fproot.crl"
    "http://vcssev142.crl.omniroot.com/vcssev142.crl"
    "http://crl.pki.abb.com/omniroot2025.crl"
    "http://crl.e-szigno.hu/rootca2009.crl"
    "http://crl.globalsign.com/gs/trustrootsha2g2.crl"
    "http://www.swissdigicert.ch/download/sdcs-root.crl"
    "http://www2.public-trust.com/crl/ct/ctroot.crl"
    "http://get-crl.certificat.com/public/opentrustrootcag1.crl"
    "http://crl.starfieldtech.com/sfroot.crl"
    "http://cdp1.pca.dfn.de/global-root-g2-ca/pub/crl/cacrl.crl"
    "http://crl.globalsign.net/jcansubrootca0.crl"
    "http://s.symcb.com/universal-root.crl"
    "https://crl.firmaprofesional.com/fproot.crl"
    "http://crl.entrust.net/ec1root.crl"
    "http://cdp1.public-trust.com/CRL/Omniroot2034.crl"
    "http://crl-3.trust.teliasonera.com/teliasonerarootcav1.crl"
    "http://ssp-crl.verisign.com/universal-root.crl"
    "http://www.d-trust.net/crl/d-trust_root_class_3_ca_2_ev_2009.crl"
    "http://acedicom.edicomgroup.com/rootca.crl"
    "http://vpssg141.crl.omniroot.com/vpssg141.crl"
    "http://get-crl.certificat.com/public/certplusrootcag2.crl"
    "http://crl.pki.wayport.net/rootca.crl"
    "http://crl.rootca1.amazontrust.com/rootca1.crl"
    "http://www.cnnic.cn/download/evrootcrl/crl1.crl"
    "http://get-crl.certificat.com/public/certplusrootcag1.crl"
    "http://cdp2.pca.dfn.de/global-root-ca/pub/crl/cacrl.crl"
    "http://cdp2.disig.sk/rootcar2/crl/rootcar2.crl"
    "http://crl1.camerfirma.com/chambersroot-2008.crl"
    "http://crl.cnnic.cn/download/rootsha2crl/CRL1.crl"
    "http://cdp2.pca.dfn.de/global-root-g2-ca/pub/crl/cacrl.crl"
    "http://crl.rootg2.amazontrust.com/rootg2.crl"
    "http://pki.qpay123.com/rootca.crl"
    "http://crl.globalsign.com/root-r5.crl"
    "http://crl.chambersign.org/chambersignroot.crl"
    "http://cdp1.public-trust.com/CRL/Omniroot2025.crl"
    "http://crl.omniroot.com/PublicSureCodeSign.crl"
    "http://crl.camerfirma.com/chambersignroot-2008.crl"
    "http://crl.d-trust.net/crl/d-trust_root_class_3_ca_2_ev_2009.crl"
    "http://www.signtrust.de/crl/dpcom/nqsig/stcert_root_ca3.crl"
    "http://crl.globalsign.net/root-r3.crl"
    "http://certificates.godaddy.com/repository/gdroot.crl"
    "http://crl.chambersign.org/chambersroot.crl"
    "http://crl.globalsign.com/root.crl"
    "http://vpscs141.crl.omniroot.com/vpscs141.crl"
    "http://crl.globalsign.com/trustrootg2.crl"
    "http://vpscs142.crl.omniroot.com/vpscs142.crl"
    "http://acedicom.edicomgroup.com/crlroot"
    "http://crl.rootca2.amazontrust.com/rootca2.crl"
    "http://vpssg142.crl.omniroot.com/vpssg142.crl"
    "http://crl.globalsign.com/gs/root-r5.crl"
    "http://www.pki.vt.edu/globalroot/crl/cacrl.crl"
    "http://crl.globalsign.net/root.crl"
    "http://crl.globalsign.com/root-r4.crl"
    "http://crl.verisign.com/universal-root.crl"
    "http://crl.swissdigicert.ch/sdcs-root2-ev.crl"
    "http://crl.certsign.ro/root.crl"
    "http://rootweb.managed.entrust.com/CRLs/EMSRootCA1.crl"
    "http://www.disig.sk/rootcar2/crl/rootcar2.crl"
    "http://www.disig.sk/rootcar1/crl/rootcar1.crl"
    "http://rootca2009-crl1.e-szigno.hu/rootca2009.crl"
    "http://crl.rootca4.amazontrust.com/rootca4.crl"
    "http://www.d-trust.net/crl/d-trust_root_class_3_ca_2_2009.crl"
    "http://crl.camerfirma.com/chambersroot.crl"
    "http://crl.globalsign.com/gs/root-r4.crl"
    "http://crl.starfieldtech.com/repository/sfroot-g2.crl"
    "http://crl.globalsign.net/root-r2.crl"
    "http://crl3.digicert.com/Omniroot2034.crl"
    "http://crl.identrust.com/publicsectorroot1.crl"
    "http://crl.globalsign.com/root-r3.crl"
    "http://crl.omniroot.com/ctglobal.crl"
    "http://get-crl.certificat.com/public/opentrustrootcag2.crl"
    "http://crl-b.pki.wayport.net/rootcag2.crl"
    "http://validation.identrust.com/crl/publicrootca1.crl"
    "http://crl.godaddy.com/gdroot.crl"
    "http://certificates.starfieldtech.com/repository/sfroot.crl"
    "http://crl.e-tugra.com/etugra_root.crl"
)

# Temporary directory to store downloaded CRLs
TEMP_DIR="/tmp/apple_crls"

# Create the temporary directory
mkdir -p "$TEMP_DIR"

# Loop over the CRL URLs
for CRL_URL in "${CRL_URLS[@]}"; do
    # Extract the filename from the URL
    FILENAME="$(basename "$CRL_URL")"
    CRL_FILE="$TEMP_DIR/$FILENAME"

    # Download the CRL
    echo "Downloading CRL from $CRL_URL..."
    curl -s -o "$CRL_FILE" "$CRL_URL"

    # Check if the download was successful
    if [[ $? -ne 0 ]]; then
        echo "Failed to download the CRL from $CRL_URL."
        continue
    fi

    # Import the CRL into the system keychain
    echo "Importing the CRL from $FILENAME into the system keychain..."
    sudo security import "$CRL_FILE" -f raw  -k "/Library/Keychains/System.keychain"

    # Check if the import was successful
    if [[ $? -ne 0 ]]; then
        echo "Failed to import the CRL from $FILENAME."
        continue
    fi
done

# Clean up the temporary directory
rm -rf "$TEMP_DIR"

echo "All CRLs have been processed."
